### ISSUE TITLE
streamline the pipeline with plink input 

### ISSUE THREAD

**Issue by 1teaspoon** [NCI-CGR/GwasQcPipeline#211]
When start with plink input files, the pipeline is able to run step by step using sub-workflows, but cannot run through a single job submission

**Comment by 1teaspoon** [comment]
make pre-flight and cgr submit work with plink input

**Comment by dorks81** [comment]
Provide path to plink files in config.yml
```
user_files:
  output_pattern: '{prefix}/{file_type}.{ext}'
  bed: /data/myplinkdata/subjects.bed
  bim: /data/myplinkdata/subjects.bim
  fam: /data/myplinkdata/subjects.fam
```
