### ISSUE TITLE
Black Version Mismatch Between Pre-commit Hooks and GitHub Actions

### ISSUE THREAD

**Issue by jaamarks** [NCI-CGR/GwasQcPipeline#323]
We've encountered a discrepancy between the Black versions used by pre-commit hooks and GitHub Actions workflows. This inconsistency leads to formatting conflicts, where files flagged as needing reformatting by GitHub Actions might not be flagged by pre-commit hooks (or vice versa).

* Pre-commit configuration (`.pre-commit-config.yaml`) specifies Black version 23.7.0.
* The Black version used by GitHub Actions workflows is 19.10b0 (as specified in `pyproject.toml`)

**Comment by jaamarks** [comment]
It seems that making the following changes allows the `cgr_gwas_qc` package to build correctly. We will need to conduct some testing to ensure everything functions as expected. Additionally, we should update the `.pre-commit-config.yml` file to ensure that the Black versions are consistent.

```toml
 packages = [
 ]

 [tool.poetry.dependencies]
python = "^3.8.1"
typer = "^0.12.5"


 [tool.poetry.dev-dependencies]
black = { version = "24.8.0" }
snakefmt = "^0.10.2"
importlib-metadata = "^8.5.0"
```
